print('Введите название файла')
a = input()
a = a.split()
file = open(a[2], 'r')
code = file.read()

code = code.replace('else', '')
code = code.replace('elif', '')
code = code.replace('min', '')
code = code.replace('max', '')
code = code.replace('import', '')
code = code.replace('replace', '')
code = code.replace('input', '')
code = code.replace('print', '')
code = code.replace('while', '')
code = code.replace('break', '')
code = code.replace('if', '')
code = code.replace('int', '')
code = code.replace('range', '')
code = code.replace('def', '')
code = code.replace('for', '')
code = code.replace(' in ', '')

code = code.replace('Дивергенция', 'else')
code = code.replace('Гермафродитизм', 'elif')
code = code.replace('Дефишенси', 'min')
code = code.replace('Доминанта', 'max')
code = code.replace('Симбиоз', 'import')
code = code.replace('Диссимиляция', 'replace')
code = code.replace('Автодупликация', 'input')
code = code.replace('Импринтинг', 'print')
code = code.replace('Дупликация', 'while')
code = code.replace('Асфиксия', 'break')
code = code.replace('Аллель', 'if')
code = code.replace('Инверсия', 'int')
code = code.replace('Рефлекс', 'range')
code = code.replace('Геном', 'def')
code = code.replace('Аккумуляция', 'for')
code = code.replace(' в ', ' in ')


exec(code)
